### PR TITLE
Added curl extension

### PR DESCRIPTION
**Pull request by guiwoda**
As discussed in #8, curl could be included as a default extension.

_PS: ignore my fork's branch name_

### CODE REVIEW

**Comment by guiwoda** [comment]
Tested via:

```
docker build -t guiwoda/php:latest .

docker run -it --rm guiwoda/php:0.2 bash
> php -m
```

**Comment by fideloper** [comment]
Thanks! I'll rebuild this as `1.2` and `latest` tag for `shippingdocker/php`

**Comment by guiwoda** [comment]
Hey @fideloper, I think you may have tagged `1.2` but not `latest` with this one!
Check it out, https://hub.docker.com/r/shippingdocker/php/tags/ says `1.2` was 8 days ago and `latest` was 14 days ago.

**Comment by fideloper** [comment]
Could be! It takes a million hours to do any one push to docker hub, could
have failed. I'll have to try again, thanks for the heads up!

**Comment by fideloper** [comment]
Updated them, should both be synced up! I deleted all my images and ran `docker-compose up -d` to ensure it all still worked - Looked good on my end, hopefully does for you as well.

Thanks again for the heads up!

**Pull request merged**
